#!/bin/bash

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

alias b=brew

alias m=mvim
export EDITOR=vim

alias g=git
alias t="tig --all"

alias v=vagrant
alias d=docker


alias bx='bundle exec'

export GOPATH="${HOME}/go"
export PATH="./bin:${GOPATH}/bin:/usr/local/opt/go/libexec/bin:${PATH}"

export RBENV_ROOT=/usr/local/var/rbenv
! which rbenv >&- || eval "$(rbenv init -)"

for profile_config in ${HOME}/.profile.d/*
do
  . "$profile_config"
done
