#!/bin/bash -e

[ -z "$DEBUG" ] || set -x

MACHINE_NAME="Eve"

main() {
  request_sudo_privileges
  preserve_sudo_privileges_until_exit
  symlink_downloads_to_desktop
  set_machine_name
  install_homebrew
  install_homebrew_cask
  setup_vim_vundle
  link_dotfiles
}

request_sudo_privileges() {
  sudo -v
}

preserve_sudo_privileges_until_exit() {
  while sleep 10
  do
    sudo -v 2>&-
  done &

  SUDO_GUARDIAN_PID="$!"
}

symlink_downloads_to_desktop() {
  pushd $HOME 1>&-
    if [ ! -L Downloads ] 
    then
      mv Downloads/* Desktop/
      sudo rm -fR Downloads
      ln -s Desktop Downloads
    fi
  popd 1>&-
}

set_machine_name() {
  MACHINE_NAME="${MACHINE_NAME:?must be defined}"

  sudo scutil --set HostName $MACHINE_NAME
  sudo scutil --set LocalHostName $MACHINE_NAME
  sudo scutil --set ComputerName $MACHINE_NAME
  dscacheutil -flushcache
}

setup_vim_vundle() {
  mkdir -p $HOME/.vim/bundle
  pushd $HOME/.vim/bundle 1>&-
    if [ ! -d Vundle.vim ]
    then
      git clone https://github.com/gmarik/Vundle.vim
      vim +PluginInstall +qall
    fi
  popd 1>&-
}

link_dotfiles() {
  local dotfile
  pushd dotfiles 1>&-
    for dotfile in *
    do
      ln -nsf $PWD/$dotfile $HOME/.$dotfile
    done
  popd 1>&-
}

install_homebrew() {
  which brew >&- || ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
}

install_homebrew_cask() {
  brew cask 2>&1 1>&- || brew install caskroom/cask/brew-cask
}

cleanup() {
 if [ -n "$SUDO_GUARDIAN_PID" ]
 then
    ! ps $SUDO_GUARDIAN_PID >&- || kill -PIPE $SUDO_GUARDIAN_PID
 fi
}

trap cleanup EXIT

main
