#!/bin/bash -e

[ -z "$DEBUG" ] || set -x

main() {
  cat > /dev/stdout <<EOF
* remove_homebrew_formulae
* remove_homebrew_casks
* remove_homebrew
* remove_dotfiles
* remove_app_symlinks
* remove_dotfile_symlinks
EOF
}

main
