#!/bin/bash -e

[ -z "$DEBUG" ] || set -x

export MY_HOSTNAME="$1"

main() {
  set_base_path
  apply_configs
  reload_modified_services
  os_x_software_update
  app_store_updates
  update_package_sources
  upgrade_installed_packages
  upgrade_installed_casks
  update_vim_plugins
  cleanup
  success
}

set_base_path() {
  SOURCE="${BASH_SOURCE[0]}"
  DIR="$( dirname "$SOURCE" )"
  while [ -h "$SOURCE" ]
  do
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="${DIR}/$SOURCE"
    DIR="$( cd -P "$(dirname "$SOURCE")" && pwd )"
  done
  BASE_PATH="$(cd "$DIR" && pwd)"
}

apply_configs() {
  local config

  (
    cd "${BASE_PATH}/libconfig"
    for config in *
    do
      # shellcheck source=/dev/null
      . "$config"
    done
  )
}

reload_modified_services() {
  killall Finder Dock
}

os_x_software_update() {
  softwareupdate --install --all
}

app_store_updates() {
  if command -v mas >&-
  then
    mas outdated | while read -r app_id_and_name
    do
      echo "Updating ${app_id_and_name##* }..."
      mas install "${app_id_and_name%% *}"
    done
  fi
}

update_package_sources() {
  brew update
}

upgrade_installed_packages() {
  brew upgrade
}

upgrade_installed_casks() {
  local cask

  brew cask list | while read -r cask
  do
    brew cask install "$cask"
  done
}

update_vim_plugins() {
  vim +PluginUpdate +PluginClean! +qall
}

cleanup() {
  brew cleanup -s --force
  brew cask cleanup
  remove_previous_cask_versions
  sudo pkill -INT softwareupdate
}

remove_previous_cask_versions() {
  local cask version_to_delete

  (
    cd /usr/local/Caskroom
    for cask in *
    do
      # shellcheck disable=SC2012
      ls -r "$cask" | tail -n +2 | while read -r version_to_delete
      do
        sudo rm -r "$cask/$version_to_delete"
      done
    done
  )
}

success() {
  printf "\\nI am yours, %s\\n\\n" "${USER}"
}

main
