#!/bin/bash -e

[ -z "$DEBUG" ] || set -x

export MY_HOSTNAME="$1"
RELOAD_SERVICES=()

main() {
  set_base_path
  apply_configs
  reload_modified_services
  os_x_software_update
  app_store_updates
  update_package_sources
  upgrade_installed_packages
  upgrade_installed_casks
  update_vim_plugins
  cleanup
  success
}

set_base_path() {
  SOURCE="${BASH_SOURCE[0]}"
  DIR="$( dirname "$SOURCE" )"
  while [ -h "$SOURCE" ]
  do
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="${DIR}/$SOURCE"
    DIR="$( cd -P "$(dirname "$SOURCE")" && pwd )"
  done
  BASE_PATH="$(cd "$DIR" && pwd)"
}

apply_configs() {
  local config

  pushd "${BASE_PATH}/libconfig" >&-
    for config in *
    do
      # shellcheck disable=SC1090
      . "$config"
    done
  popd >&-
}

reload_modified_services() {
  local modified_services=(${RELOAD_SERVICES[@]:?must be defined})
  local modified_services_uniq=(
    $(printf "%s\n" "${modified_services[@]}" | sort -u)
  )

  killall "${modified_services_uniq[@]}"
}

os_x_software_update() {
  softwareupdate --install --all
}

app_store_updates() {
  if which mas >&-
  then
    mas outdated | while read -r app_id_and_name
    do
      echo "Updating ${app_id_and_name##* }..."
      mas install "${app_id_and_name%% *}"
    done
  fi
}

update_package_sources() {
  brew update
}

upgrade_installed_packages() {
  brew upgrade --all
}

upgrade_installed_casks() {
  local cask

  brew cask list | while read -r cask
  do
    brew cask install "$cask"
  done
}

update_vim_plugins() {
  vim +PluginUpdate +PluginClean! +qall
}

cleanup() {
  brew cleanup -s --force
  brew cask cleanup
  sudo pkill -INT softwareupdate
}

success() {
  echo -e "\nI am yours, ${USER}\n"
}

main
