#!/bin/bash -e

[ -z "$DEBUG" ] || set -x

MY_HOSTNAME="$1"
RELOAD_SERVICES=()

main() {
  request_sudo_privileges
  preserve_sudo_privileges_until_exit
  load_all_configs

  # homebrew
  install_homebrew
  install_homebrew_taps
  install_homebrew_formulae
  setup_htop
  install_homebrew_casks
  install_fonts

  # go
  install_go_packages

  # vim
  setup_vim_vundle
  setup_you_complete_me

  reload_modified_services
  success
}

request_sudo_privileges() {
  sudo -v
}

preserve_sudo_privileges_until_exit() {
  while sleep 10
  do
    sudo -v 2>&-
  done &

  SUDO_GUARDIAN_PID="$!"
}

load_all_configs() {
  local config

  pushd libexec >&-
    for config in *
    do
      . "$config"
    done
  popd >&-
}

setup_vim_vundle() {
  mkdir -p $HOME/.vim/bundle
  pushd $HOME/.vim/bundle >&-
    if [ ! -d Vundle.vim ]
    then
      git clone https://github.com/gmarik/Vundle.vim
      vim +PluginInstall +qall
    fi
  popd >&-
}

setup_you_complete_me() {
  local ycm_dir="${HOME}/.vim/bundle/YouCompleteMe"
  if [ -e "$ycm_dir" ]
  then
    pushd "$ycm_dir" >&-
      if ! ls .installed* >&- 2>&-
      then
        ./install.sh
        touch .installed.$(date +"%Y%m%d")
      fi
    popd >&-
  fi
}

install_fonts() {
  local installed_casks="$(brew cask list)"
  local font

  pushd homebrew/fonts >&-
    for font in *
    do
      grep "$font" >&- <<< "$installed_casks" || brew cask install "$font"
    done
  popd >&-
}

install_homebrew() {
  which brew >&- || ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
}

install_homebrew_formulae() {
  local installed_formulae="$(brew list)"
  local formula

  pushd homebrew/formulae >&-
    for formula in *
    do
      grep "$formula" >&- <<< "$installed_formulae" || brew install "$formula"
    done
  popd >&-
}

install_homebrew_casks() {
  local installed_casks="$(brew cask list)"
  local cask

  pushd homebrew/casks >&-
    for cask in *
    do
      grep "$cask" >&- <<< "$installed_casks" || brew cask install "$cask"
    done
  popd >&-
}

install_go_packages() {
  local pkg

  pushd go/packages >&-
    for pkg in *
    do
      go get ${pkg//\~//}
    done
  popd >&-
}

setup_htop() {
  local htop_bins=$(find /usr/local/Cellar -name htop -perm +111 -type f)
  local htop_bin

  for htop_bin in ${htop_bins[@]}
  do
    sudo chown root:wheel "$htop_bin"
    sudo chmod u+s "$htop_bin"
  done
}

install_homebrew_taps() {
  local installed_taps="$(brew tap)"

  pushd homebrew/taps >&-
    local tap
    for tap in *
    do
      tap="${tap//\~//}"
      grep "$tap" >&- <<< "$installed_taps" || brew tap "$tap"
    done
  popd >&-
}

reload_modified_services() {
  local modified_services=${RELOAD_SERVICES[@]:?must be defined}
  local modified_services_uniq=(
    $(printf "%s\n" ${modified_services[@]} | sort -u)
  )

  killall ${modified_services_uniq[@]}
}

success() {
  echo -e "\nI am yours, ${USER}\n"
}

cleanup() {
 if [ -n "$SUDO_GUARDIAN_PID" ]
 then
    ! ps $SUDO_GUARDIAN_PID >&- || kill -PIPE $SUDO_GUARDIAN_PID
 fi
}

trap cleanup EXIT

main
