#!/bin/bash -e

[ -z "$DEBUG" ] || set -x

main() {
  os_x_software_update
  app_store_updates
  update_package_sources
  upgrade_installed_packages
  upgrade_installed_casks
  # shellcheck disable=SC1091
  . libconfig/homebrew_htop
  # update go pkgs
  update_vim_plugins
  cleanup
}

os_x_software_update() {
  softwareupdate --install --all
}

app_store_updates() {
  if which mas >&-
  then
    mas outdated | while read -r app_id_and_name
    do
      echo "Updating ${app_id_and_name##* }..."
      mas install "${app_id_and_name%% *}"
    done
  fi
}

update_package_sources() {
  brew update
}

upgrade_installed_packages() {
  brew upgrade --all
}

upgrade_installed_casks() {
  local cask

  brew cask list | while read -r cask
  do
    brew cask install "$cask"
  done
}

update_vim_plugins() {
  vim +PluginUpdate +PluginClean! +qall
}

remove_unused_casks() {
  local cask version_to_delete
  pushd /opt/homebrew-cask/Caskroom >&-
    for cask in *
    do
      # shellcheck disable=SC2012
      ls -r "$cask" | tail -n +2 | while read -r version_to_delete
      do
        sudo rm -r "${cask:?}/$version_to_delete"
      done
    done
  popd
}

cleanup() {
  brew cleanup -s --force
  brew cask cleanup
  remove_unused_casks
  sudo pkill -INT softwareupdate
}

main
