#!/bin/bash -e

[ -z "$DEBUG" ] || set -x

main() {
  os_x_software_update
  update_package_sources
  upgrade_installed_packages
  cleanup
}

os_x_software_update() {
  softwareupdate --install --all
}

update_package_sources() {
  brew update
}

upgrade_installed_packages() {
  brew upgrade
}

cleanup() {
  brew cleanup -s --force
}

main
