#!/bin/bash -e

installed_casks="$(brew cask list)"

pushd "${BASE_PATH}/homebrew/casks" >&-
  for cask in *
  do
    grep -qe "^$cask" < <(echo "$installed_casks") || brew cask install "$cask"
  done
popd >&-
