#!/bin/bash

if brew uninstall ctags 2>&-
then
  echo "ctags has been forked and renamed to Universal Ctags"
fi

if brew uninstall htop-osx 2>&-
then
  echo "Native OS X htop now uses a different formula name"
fi

if brew uninstall brew-cask 2>&-
then
  echo "Homebrew handles Homebrew-Cask updates automatically"
fi
