#!/bin/bash -e

installed_taps="$(brew tap)"

pushd "${BASE_PATH}/homebrew/taps" >&-
  local tap
  for tap in *
  do
    tap="${tap//\~//}"
    grep "$tap" >&- <<< "$installed_taps" || brew tap "$tap"
  done
popd >&-
