#!/bin/bash

brew_path="$(brew --prefix)"
dnsmasq_path="$(brew --prefix dnsmasq)"
dnsmasq_service="homebrew.mxcl.dnsmasq"
dnsmasq_plist="${dnsmasq_service}.plist"
domain="$(hostname)"

main() {
  use_local_dns_to_resolve_domain
  supervise
  use_local_dns_when_resolving
}

use_local_dns_to_resolve_domain() {
  grep -c "$domain" "${brew_path}/etc/dnsmasq.conf" &>/dev/null ||
  echo "address=/.${domain}/127.0.0.1" >> "${brew_path}/etc/dnsmasq.conf"
}

supervise() {
  sudo bash -c "
    [ -f /Library/LaunchDaemonscp/$dnsmasq_plist ] ||
    cp ${dnsmasq_path}/$dnsmasq_plist /Library/LaunchDaemons

    launchctl list $dnsmasq_service &>/dev/null ||
    launchctl load -w /Library/LaunchDaemons/$dnsmasq_plist
  "
}

use_local_dns_when_resolving() {
  sudo bash -c "
    mkdir -p /etc/resolver
    bash -c echo 'nameserver 127.0.0.1' > /etc/resolver/$domain
  "
}

main
