#!/bin/bash -e

vundle_bundle="${HOME}/.vim/bundle"
vundle_repository="https://github.com/gmarik/Vundle.vim"

mkdir -p "$vundle_bundle"
(
  cd "$vundle_bundle"
  if [ ! -d Vundle.vim ]
  then
    git clone "$vundle_repository"
    vim +PluginInstall +qall
  fi
)
