#!/bin/bash -e

installed_casks="$(brew cask list)"

pushd "${BASE_PATH}/homebrew/fonts" >&-
  for font in *
  do
    grep "$font" >&- <<< "$installed_casks" || brew cask install "$font"
  done
popd >&-
