#!/bin/bash

installed_formulae="$(brew list)"

formula_not_installed?() {
  local formula="${1:?formula must be provided}"

  ! grep "$formula" >&- <<< "$installed_formulae"
}

pushd "${BASE_PATH}/homebrew/formulae" >&-
  for formula in *
  do
    formula_options="$(cat "$formula")"
    if formula_not_installed? "$formula"
    then
      if [ -z "$formula_options" ]
      then
        brew install "$formula"
      else
        brew install "$formula" "$formula_options"
      fi
    fi
  done
popd >&-
