#!/bin/bash -e

installed_taps="$(brew tap)"

pushd "${BASE_PATH}/homebrew/taps" >&-
  local tap
  for tap in *
  do
    tap="${tap//\~//}"
    [[ $installed_taps =~ $tap ]] || brew tap "$tap"
  done
popd >&-
