#!/bin/bash -e

installed_formulae="$(brew list)"

(
  cd "${BASE_PATH}/homebrew/formulae"
  for formula in *
  do
    if ! grep -qe "^$formula" < <(echo "$installed_formulae")
    then
      formula_options="$(cat "$formula")"
      bash -c "brew install $formula $formula_options"
    fi
  done
)
