#!/bin/bash -e

homebrew_bash_bin=/usr/local/bin/bash

if [ -x "$homebrew_bash_bin" ]
then
  grep "$homebrew_bash_bin" /etc/shells >&- ||
    echo "$homebrew_bash_bin" | sudo tee -a /etc/shells >&-

  [ "$SHELL" == "$homebrew_bash_bin" ] ||
    (chsh -s "$homebrew_bash_bin" && echo -e "\nRestart to complete this setup\n")
fi
