#!/bin/bash

# Append to history file, don't overwrite it.
shopt -s histappend

# Don't put duplicate lines in the history. See bash(1) for more options.
export HISTCONTROL=ignoredups

# Enable Homebrew bash completion
[ ! -f /usr/local/etc/bash_completion ] ||
  . /usr/local/etc/bash_completion
