#!/bin/bash

alias b="bosh"

alias bt="bosh target"
alias bts="bosh targets"

alias bv="bosh vms --vitals"

# Releases
alias br="bosh releases"
alias brc="bosh create release"
alias brcf="bosh create release --force"
alias bru="bosh upload release"
alias brd="bosh delete release"

# Deployments
alias bd="bosh deployment"
alias bdn="bosh -n deploy"
alias bds="bosh deployments"
alias bdd="bosh delete deployment"

# Manifests
alias bmd="bosh download manifest"

# Stemcells
alias bs="bosh stemcells"
alias bsu="bosh upload stemcell"

# Errands
alias be="bosh errands"
alias ber="bosh run errand"
