#!/bin/bash

alias p=brew
alias s="brew search"

i() {
  brew install "$@" || brew cask install "$@"
}

ri() {
  brew reinstall "$@" || brew cask reinstall "$@"
}

upg() {
  brew upgrade "$@" || brew cask reinstall "$@"
}
