#!/bin/bash

skip_completions_with_incorrect_syntaxes() {
  [[ "$completion" =~ aria2|docker ]]
}

if [ -d /usr/local/etc/bash_completion.d ]
then
  for completion in /usr/local/etc/bash_completion.d/*
  do
    skip_completions_with_incorrect_syntaxes || . "$completion"
  done
fi
