#!/bin/bash

# Build Erlang from https://github.com/erlang/otp/releases
KERL_BUILD_BACKEND=git
export KERL_BUILD_BACKEND

# Get shell history out of the box with Erlang/OTP 20
export ERL_AFLAGS="-kernel shell_history enabled"

# Disable Erlang crash dumps
export ERL_CRASH_DUMP_SECONDS=0

timestamp() {
  date +'%Y%m%d_%H%M%S'
}

eobs() {
  erl -sname "observe-$(timestamp)" -hidden \
    -setcookie "${COOKIE:?must be set}" \
    -run observer
}

esh() {
  erl -sname "remote-$(timestamp)" -hidden \
    -setcookie "${COOKIE:?must be set}" \
    -remsh "${RMQ_NODE:?must be set}"
}

edump() {
  "$(find -L /usr/local/lib/erlang -name 'cdv')" \
    "${1:?first argument must be a valid erl_crash.dump file}"
}
