#!/bin/bash

GITHUB_USER=gerhard
export GITHUB_USER

if command -v lpass >&-
then
  if lpass status --quiet
  then
    GITHUB_PERSONAL_ACCESS_TOKEN="$(lpass show 14390611815915318 --notes)"
    export GITHUB_PERSONAL_ACCESS_TOKEN
    GITHUB_TOKEN="$GITHUB_PERSONAL_ACCESS_TOKEN"
    export GITHUB_TOKEN
  fi
fi
