#!/bin/bash

enable_stack_bash_autocompletion() {
  eval "$(stack --bash-completion-script stack)"
}

add_stack_to_path() {
  export PATH="$HOME/.local/bin:$PATH"
}

if which stack >&-
then
  enable_stack_bash_autocompletion
  add_stack_to_path
fi
