#!/bin/bash

add_homebrew_sbin_to_path() {
  # dnsmasq, unbound-*, etc. executables are stored here
  export PATH="/usr/local/sbin:$PATH"
}

load_homebrew_github_api_key_from_lastpass() {
  if command -v lpass >&-
  then
    lpass status --quiet || return 0
    HOMEBREW_GITHUB_API_TOKEN="$(lpass show 8925286498423176565 --notes)"
    export HOMEBREW_GITHUB_API_TOKEN
  fi
}

add_homebrew_sbin_to_path
load_homebrew_github_api_key_from_lastpass
