#!/bin/bash

response_time() {
  local url
  url="$1"

  while :
  do
    curl -sL -o /dev/null \
    -w '%{http_code} dns:%{time_namelookup} tcp:%{time_connect} tls:%{time_appconnect} total:%{time_total}\n' \
    "$url"
  done
}

response_headers() {
  local url
  url="$1"

  curl -svL -o /dev/null "$url"
}
