#!/bin/bash

alias bx="bundle exec"

alias bl="bundle list"

alias bi="bundle install"
alias bu="bundle update"

alias bout="bundle outdated"

if which rbenv >&-
then
  export RBENV_ROOT=/usr/local/var/rbenv
  eval "$(rbenv init -)"
fi
