#!/bin/bash

rotate_ssh_key() {
  _generate_new_ssh_key
  _add_new_ssh_key_to_keychain
  _copy_new_ssh_pub_key
  _start_rotations
  _github
  _bitbucket
  _digitalocean
  _packet
  _ssh_hosts
  _remove_old_ssh_key
  _end_rotations
}

_generate_new_ssh_key() {
  # https://blog.g3rt.nl/upgrade-your-ssh-keys.html
  ssh-keygen -t ed25519 -a 100 -f "$(_new_ed25519_ssh_key)"
}

_add_new_ssh_key_to_keychain() {
  ssh-add -K "$(_new_ed25519_ssh_key)"
}

_copy_new_ssh_pub_key() {
  pbcopy < "$(_new_ed25519_ssh_key).pub"
  echo "
The public part of your new SSH key is in your clipboard"
}

_new_ed25519_ssh_key() {
  echo ~/.ssh/"$(hostname)_$(date +'%Y%m%d')_ed25519"
}

_start_rotations() {
  echo "Time to start rotating your old SSH keys, press enter as you make progress"
}

_github() {
  read -rp "
I added my new SSH key to GitHub https://github.com/settings/keys
I removed my old SSH key from GitHub (maybe) " -n 1
}

_bitbucket() {
  read -rp "
I added my new SSH key to Bitbucket https://bitbucket.org/account/user/gerhardlazu/ssh-keys/
I removed my old SSH key from Bitbucket (maybe) " -n 1
}

_digitalocean() {
  read -rp "
I added my new SSH key to DigitalOcean https://cloud.digitalocean.com/account/security?i=085bd5
I removed my old SSH key from DigitalOcean (maybe) " -n 1
}

_packet() {
  read -rp "
I added my new SSH key to Packet https://app.packet.net/users/a4912cea-5687-495f-8401-489d7a69b5fd/ssh
I removed my old SSH key from Packet (maybe) " -n 1
}

_ssh_hosts() {
  awk '/^Host / { system("ssh-copy-id -i '"$(_new_ed25519_ssh_key)"' " $2) }' "$HOME/.ssh/config"
}

_remove_old_ssh_key() {
  read -rp "
I've removed my old SSH key from SSH Agent & Keychain" -n 1
}

_end_rotations() {
  echo "
👏 Yet another successfull SSH key rotation 👏
"
}
