#!/bin/bash

mp3_dl() {
  local youtube_url
  youtube_url="${1:?First argument must be a YouTube URL}"
  shift 1

  youtube-dl \
    --extract-audio --audio-format mp3 --audio-quality 0 --embed-thumbnail \
    -o '%(title)s.%(ext)s' --no-mtime --ignore-errors \
    "$youtube_url" "$@"
}

mkv_dl() {
  local youtube_url
  youtube_url="${1:?First argument must be a YouTube URL}"
  shift 1

  youtube-dl \
    --keep-video --recode-video mkv \
    -o '%(title)s.%(ext)s' --no-mtime --ignore-errors \
    "$youtube_url" "$@"
}

ydld() {
  local youtube_url
  youtube_url="${1:?First argument must be a YouTube URL}"
  shift 1

  mkv_dl "$youtube_url" "$@"
  mp3_dl "$youtube_url" "$@"
}

pdld() {
  local youtube_playlist_url
  youtube_playlist_url="${1:?First argument must be YouTube Playlist URL}"
  shift 1

  youtube-dl --download-archive pdld.txt "$youtube_playlist_url" "$@"
  ydld "$youtube_playlist_url" "$@"
}
